#   This file fixes dependencies to exact versions:
#   those set in the snapshot, amended by those listed in extra-deps.
#   You still need to add dependencies to the `.cabal` file, and the
#   verison ranges there (if any) must include the versions specified here.
#
#   Documentation for this file is found at:
#   • https://docs.haskellstack.org/en/stable/configure/yaml/

snapshot: lts-22.44
packages: [.]       # Paths with *.cabal files in this repo.
extra-deps: []      # Deps we override or add to the snapshot.
