# Documentation for this file:
#   https://www.netlify.com/docs/netlify-toml-reference/

[build]
    command = "# no build command"
    publish = "."

[[headers]]
    for = "/wiki/*"
    [headers.values]
        Content-type = "text/html; charset=utf-8"
